package com.moonshot.rob.model.wsdl;

import jakarta.annotation.Generated;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", name = "CalculatorService")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", comments = "Apache CXF 4.0.2")
public interface CalculatorService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int add(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addArray", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddArray")
    @ResponseWrapper(localName = "addArrayResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddArrayResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int addArray(

        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.Integer> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "subtract", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.SubtractResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int subtract(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "divide", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.Divide")
    @ResponseWrapper(localName = "divideResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.DivideResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int divide(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addList", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddList")
    @ResponseWrapper(localName = "addListResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddListResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int addList(

        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.Integer> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addNumberAndOperands", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddNumberAndOperands")
    @ResponseWrapper(localName = "addNumberAndOperandsResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddNumberAndOperandsResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int addNumberAndOperands(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        com.moonshot.rob.model.wsdl.Operands arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addOperands", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddOperands")
    @ResponseWrapper(localName = "addOperandsResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.AddOperandsResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public com.moonshot.rob.model.wsdl.Result addOperands(

        @WebParam(name = "arg0", targetNamespace = "")
        com.moonshot.rob.model.wsdl.Operands arg0
    );

    @WebMethod
    @RequestWrapper(localName = "multiply", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://www.jboss.org/eap/quickstarts/wscalculator/Calculator", className = "com.moonshot.rob.model.wsdl.MultiplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava")
    public int multiply(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
